import pyspark.sql.types as T

"""
This python file contains the schema of all the required datasets / tables from SAP.
"""

MARA_SCHEMA = T.StructType(
    [
        T.StructField("MANDT", T.StringType()),
        T.StructField("MATNR", T.StringType()),
        T.StructField("ERSDA", T.DateType()),
        T.StructField("ERNAM", T.StringType()),
        T.StructField("LAEDA", T.DateType()),
        T.StructField("AENAM", T.StringType()),
        T.StructField("VPSTA", T.StringType()),
        T.StructField("PSTAT", T.StringType()),
        T.StructField("LVORM", T.StringType()),
        T.StructField("MTART", T.StringType()),
        T.StructField("MBRSH", T.StringType()),
        T.StructField("MATKL", T.StringType()),
        T.StructField("BISMT", T.StringType()),
        T.StructField("MEINS", T.StringType()),
        T.StructField("BSTME", T.StringType()),
        T.StructField("ZEINR", T.StringType()),
        T.StructField("ZEIAR", T.StringType()),
        T.StructField("ZEIVR", T.StringType()),
        T.StructField("ZEIFO", T.StringType()),
        T.StructField("AESZN", T.StringType()),
        T.StructField("BLATT", T.StringType()),
        T.StructField("BLANZ", T.StringType()),
        T.StructField("FERTH", T.StringType()),
        T.StructField("FORMT", T.StringType()),
        T.StructField("GROES", T.StringType()),
        T.StructField("WRKST", T.StringType()),
        T.StructField("NORMT", T.StringType()),
        T.StructField("LABOR", T.StringType()),
        T.StructField("EKWSL", T.StringType()),
        T.StructField("BRGEW", T.DoubleType()),
        T.StructField("NTGEW", T.DoubleType()),
        T.StructField("GEWEI", T.StringType()),
        T.StructField("VOLUM", T.DoubleType()),
        T.StructField("VOLEH", T.StringType()),
        T.StructField("BEHVO", T.StringType()),
        T.StructField("RAUBE", T.StringType()),
        T.StructField("TEMPB", T.StringType()),
        T.StructField("DISST", T.StringType()),
        T.StructField("TRAGR", T.StringType()),
        T.StructField("STOFF", T.StringType()),
        T.StructField("SPART", T.StringType()),
        T.StructField("KUNNR", T.StringType()),
        T.StructField("EANNR", T.StringType()),
        T.StructField("WESCH", T.DoubleType()),
        T.StructField("BWVOR", T.StringType()),
        T.StructField("BWSCL", T.StringType()),
        T.StructField("SAISO", T.StringType()),
        T.StructField("ETIAR", T.StringType()),
        T.StructField("ETIFO", T.StringType()),
        T.StructField("ENTAR", T.StringType()),
        T.StructField("EAN11", T.StringType()),
        T.StructField("NUMTP", T.StringType()),
        T.StructField("LAENG", T.DoubleType()),
        T.StructField("BREIT", T.DoubleType()),
        T.StructField("HOEHE", T.DoubleType()),
        T.StructField("MEABM", T.StringType()),
        T.StructField("PRDHA", T.StringType()),
        T.StructField("AEKLK", T.StringType()),
        T.StructField("CADKZ", T.StringType()),
        T.StructField("QMPUR", T.StringType()),
        T.StructField("ERGEW", T.DoubleType()),
        T.StructField("ERGEI", T.StringType()),
        T.StructField("ERVOL", T.DoubleType()),
        T.StructField("ERVOE", T.StringType()),
        T.StructField("GEWTO", T.DoubleType()),
        T.StructField("VOLTO", T.DoubleType()),
        T.StructField("VABME", T.StringType()),
        T.StructField("KZREV", T.StringType()),
        T.StructField("KZKFG", T.StringType()),
        T.StructField("XCHPF", T.StringType()),
        T.StructField("VHART", T.StringType()),
        T.StructField("FUELG", T.DoubleType()),
        T.StructField("STFAK", T.IntegerType()),
        T.StructField("MAGRV", T.StringType()),
        T.StructField("BEGRU", T.StringType()),
        T.StructField("DATAB", T.DateType()),
        T.StructField("LIQDT", T.DateType()),
        T.StructField("SAISJ", T.StringType()),
        T.StructField("PLGTP", T.StringType()),
        T.StructField("MLGUT", T.StringType()),
        T.StructField("EXTWG", T.StringType()),
        T.StructField("SATNR", T.StringType()),
        T.StructField("ATTYP", T.StringType()),
        T.StructField("KZKUP", T.StringType()),
        T.StructField("KZNFM", T.StringType()),
        T.StructField("PMATA", T.StringType()),
        T.StructField("MSTAE", T.StringType()),
        T.StructField("MSTAV", T.StringType()),
        T.StructField("MSTDE", T.DateType()),
        T.StructField("MSTDV", T.DateType()),
        T.StructField("TAKLV", T.StringType()),
        T.StructField("RBNRM", T.StringType()),
        T.StructField("MHDRZ", T.DoubleType()),
        T.StructField("MHDHB", T.DoubleType()),
        T.StructField("MHDLP", T.DoubleType()),
        T.StructField("INHME", T.StringType()),
        T.StructField("INHAL", T.DoubleType()),
        T.StructField("VPREH", T.DoubleType()),
        T.StructField("ETIAG", T.StringType()),
        T.StructField("INHBR", T.DoubleType()),
        T.StructField("CMETH", T.StringType()),
        T.StructField("CUOBF", T.StringType()),
        T.StructField("KZUMW", T.StringType()),
        T.StructField("KOSCH", T.StringType()),
        T.StructField("SPROF", T.StringType()),
        T.StructField("NRFHG", T.StringType()),
        T.StructField("MFRPN", T.StringType()),
        T.StructField("MFRNR", T.StringType()),
        T.StructField("BMATN", T.StringType()),
        T.StructField("MPROF", T.StringType()),
        T.StructField("KZWSM", T.StringType()),
        T.StructField("SAITY", T.StringType()),
        T.StructField("PROFL", T.StringType()),
        T.StructField("IHIVI", T.StringType()),
        T.StructField("ILOOS", T.StringType()),
        T.StructField("SERLV", T.StringType()),
        T.StructField("KZGVH", T.StringType()),
        T.StructField("XGCHP", T.StringType()),
        T.StructField("KZEFF", T.StringType()),
        T.StructField("COMPL", T.StringType()),
        T.StructField("IPRKZ", T.StringType()),
        T.StructField("RDMHD", T.StringType()),
        T.StructField("PRZUS", T.StringType()),
        T.StructField("MTPOS_MARA", T.StringType()),
        T.StructField("BFLME", T.StringType()),
        T.StructField("MATFI", T.StringType()),
        T.StructField("CMREL", T.StringType()),
        T.StructField("BBTYP", T.StringType()),
        T.StructField("SLED_BBD", T.StringType()),
        T.StructField("GTIN_VARIANT", T.StringType()),
        T.StructField("GENNR", T.StringType()),
        T.StructField("RMATP", T.StringType()),
        T.StructField("ZZOLDPRODH", T.StringType()),
        T.StructField("ZZBUSNSEG", T.StringType()),
        T.StructField("ZZPRDINIT", T.StringType()),
        T.StructField("ZZPCKQTY", T.StringType()),
        T.StructField("ZZPCKQUOM", T.StringType()),
        T.StructField("ZZCASEQTY", T.StringType()),
        T.StructField("ZZPKGSORTKEY", T.StringType()),
        T.StructField("ZZPKGDESC", T.StringType()),
        T.StructField("ZZMDL", T.StringType()),
        T.StructField("ZZOUTR_PCKGNG", T.StringType()),
        T.StructField("ZZREL", T.StringType()),
        T.StructField("ZZRELCODE", T.StringType()),
        T.StructField("ZZPKGCAPACITY", T.StringType()),
        T.StructField("ZZMAT_SEG", T.StringType()),
        T.StructField("ZZNPH", T.StringType()),
        T.StructField("ZZMAT_SBU", T.StringType()),
        T.StructField("ZZMAT_GPH", T.StringType()),
        T.StructField("ZZMDGM", T.StringType()),
        T.StructField("ZZMSBU_PL", T.StringType()),
        T.StructField("ZZMGPH_PL", T.StringType()),
        T.StructField("ZZORIGSRC", T.StringType()),
        T.StructField("ZZPRODMAN", T.StringType()),
        T.StructField("ZZREVCATE", T.StringType()),
        T.StructField("ZZLAUNCHD", T.DateType()),
        T.StructField("ZZPRODSTEW", T.StringType()),
        T.StructField("ZZBRAND_PF", T.StringType()),
        T.StructField("ZZICM_COGS", T.StringType()),
        T.StructField("BRAND_ID", T.StringType()),
        T.StructField("ZZTAXGROUP", T.StringType()),
        T.StructField("ZZMATTAXCLASS", T.StringType()),
        T.StructField("ZZHW_ME", T.StringType()),
        T.StructField("MATNR_CLEAN", T.StringType()),
        T.StructField("sur_pkey", T.StringType()),
    ]
)

MARC_SCHEMA = T.StructType(
    [
        T.StructField("MANDT", T.StringType()),
        T.StructField("MATNR", T.StringType()),
        T.StructField("WERKS", T.StringType()),
        T.StructField("PSTAT", T.StringType()),
        T.StructField("LVORM", T.StringType()),
        T.StructField("BWTTY", T.StringType()),
        T.StructField("XCHAR", T.StringType()),
        T.StructField("MMSTA", T.StringType()),
        T.StructField("MMSTD", T.DateType()),
        T.StructField("MAABC", T.StringType()),
        T.StructField("KZKRI", T.StringType()),
        T.StructField("EKGRP", T.StringType()),
        T.StructField("AUSME", T.StringType()),
        T.StructField("DISPR", T.StringType()),
        T.StructField("DISMM", T.StringType()),
        T.StructField("DISPO", T.StringType()),
        T.StructField("KZDIE", T.StringType()),
        T.StructField("PLIFZ", T.DoubleType()),
        T.StructField("WEBAZ", T.DoubleType()),
        T.StructField("PERKZ", T.StringType()),
        T.StructField("AUSSS", T.DoubleType()),
        T.StructField("DISLS", T.StringType()),
        T.StructField("BESKZ", T.StringType()),
        T.StructField("SOBSL", T.StringType()),
        T.StructField("MINBE", T.DoubleType()),
        T.StructField("EISBE", T.DoubleType()),
        T.StructField("BSTMI", T.DoubleType()),
        T.StructField("BSTMA", T.DoubleType()),
        T.StructField("BSTFE", T.DoubleType()),
        T.StructField("BSTRF", T.DoubleType()),
        T.StructField("MABST", T.DoubleType()),
        T.StructField("LOSFX", T.DoubleType()),
        T.StructField("SBDKZ", T.StringType()),
        T.StructField("LAGPR", T.StringType()),
        T.StructField("ALTSL", T.StringType()),
        T.StructField("KZAUS", T.StringType()),
        T.StructField("AUSDT", T.DateType()),
        T.StructField("NFMAT", T.StringType()),
        T.StructField("KZBED", T.StringType()),
        T.StructField("MISKZ", T.StringType()),
        T.StructField("FHORI", T.StringType()),
        T.StructField("PFREI", T.StringType()),
        T.StructField("FFREI", T.StringType()),
        T.StructField("RGEKZ", T.StringType()),
        T.StructField("FEVOR", T.StringType()),
        T.StructField("BEARZ", T.DoubleType()),
        T.StructField("RUEZT", T.DoubleType()),
        T.StructField("TRANZ", T.DoubleType()),
        T.StructField("BASMG", T.DoubleType()),
        T.StructField("DZEIT", T.DoubleType()),
        T.StructField("MAXLZ", T.DoubleType()),
        T.StructField("LZEIH", T.StringType()),
        T.StructField("KZPRO", T.StringType()),
        T.StructField("GPMKZ", T.StringType()),
        T.StructField("UEETO", T.DoubleType()),
        T.StructField("UEETK", T.StringType()),
        T.StructField("UNETO", T.DoubleType()),
        T.StructField("WZEIT", T.DoubleType()),
        T.StructField("ATPKZ", T.StringType()),
        T.StructField("VZUSL", T.DoubleType()),
        T.StructField("HERBL", T.StringType()),
        T.StructField("INSMK", T.StringType()),
        T.StructField("SPROZ", T.DoubleType()),
        T.StructField("QUAZT", T.DoubleType()),
        T.StructField("SSQSS", T.StringType()),
        T.StructField("MPDAU", T.DoubleType()),
        T.StructField("KZPPV", T.StringType()),
        T.StructField("KZDKZ", T.StringType()),
        T.StructField("WSTGH", T.DoubleType()),
        T.StructField("PRFRQ", T.DoubleType()),
        T.StructField("NKMPR", T.DateType()),
        T.StructField("UMLMC", T.DoubleType()),
        T.StructField("LADGR", T.StringType()),
        T.StructField("XCHPF", T.StringType()),
        T.StructField("USEQU", T.StringType()),
        T.StructField("LGRAD", T.DoubleType()),
        T.StructField("AUFTL", T.StringType()),
        T.StructField("PLVAR", T.StringType()),
        T.StructField("OTYPE", T.StringType()),
        T.StructField("OBJID", T.StringType()),
        T.StructField("MTVFP", T.StringType()),
        T.StructField("PERIV", T.StringType()),
        T.StructField("KZKFK", T.StringType()),
        T.StructField("VRVEZ", T.DoubleType()),
        T.StructField("VBAMG", T.DoubleType()),
        T.StructField("VBEAZ", T.DoubleType()),
        T.StructField("LIZYK", T.StringType()),
        T.StructField("BWSCL", T.StringType()),
        T.StructField("KAUTB", T.StringType()),
        T.StructField("KORDB", T.StringType()),
        T.StructField("STAWN", T.StringType()),
        T.StructField("HERKL", T.StringType()),
        T.StructField("HERKR", T.StringType()),
        T.StructField("EXPME", T.StringType()),
        T.StructField("MTVER", T.StringType()),
        T.StructField("PRCTR", T.StringType()),
        T.StructField("TRAME", T.DoubleType()),
        T.StructField("MRPPP", T.StringType()),
        T.StructField("SAUFT", T.StringType()),
        T.StructField("FXHOR", T.StringType()),
        T.StructField("VRMOD", T.StringType()),
        T.StructField("VINT1", T.StringType()),
        T.StructField("VINT2", T.StringType()),
        T.StructField("VERKZ", T.StringType()),
        T.StructField("STLAL", T.StringType()),
        T.StructField("STLAN", T.StringType()),
        T.StructField("PLNNR", T.StringType()),
        T.StructField("APLAL", T.StringType()),
        T.StructField("LOSGR", T.DoubleType()),
        T.StructField("SOBSK", T.StringType()),
        T.StructField("FRTME", T.StringType()),
        T.StructField("LGPRO", T.StringType()),
        T.StructField("DISGR", T.StringType()),
        T.StructField("KAUSF", T.DoubleType()),
        T.StructField("QZGTP", T.StringType()),
        T.StructField("QMATV", T.StringType()),
        T.StructField("TAKZT", T.DoubleType()),
        T.StructField("RWPRO", T.StringType()),
        T.StructField("COPAM", T.StringType()),
        T.StructField("ABCIN", T.StringType()),
        T.StructField("AWSLS", T.StringType()),
        T.StructField("SERNP", T.StringType()),
        T.StructField("CUOBJ", T.StringType()),
        T.StructField("STDPD", T.StringType()),
        T.StructField("SFEPR", T.StringType()),
        T.StructField("XMCNG", T.StringType()),
        T.StructField("QSSYS", T.StringType()),
        T.StructField("LFRHY", T.StringType()),
        T.StructField("RDPRF", T.StringType()),
        T.StructField("VRBMT", T.StringType()),
        T.StructField("VRBWK", T.StringType()),
        T.StructField("VRBDT", T.DateType()),
        T.StructField("VRBFK", T.DoubleType()),
        T.StructField("AUTRU", T.StringType()),
        T.StructField("PREFE", T.StringType()),
        T.StructField("PRENC", T.StringType()),
        T.StructField("PRENO", T.StringType()),
        T.StructField("PREND", T.DateType()),
        T.StructField("PRENE", T.StringType()),
        T.StructField("PRENG", T.DateType()),
        T.StructField("ITARK", T.StringType()),
        T.StructField("SERVG", T.StringType()),
        T.StructField("KZKUP", T.StringType()),
        T.StructField("STRGR", T.StringType()),
        T.StructField("CUOBV", T.StringType()),
        T.StructField("LGFSB", T.StringType()),
        T.StructField("SCHGT", T.StringType()),
        T.StructField("CCFIX", T.StringType()),
        T.StructField("EPRIO", T.StringType()),
        T.StructField("QMATA", T.StringType()),
        T.StructField("RESVP", T.DoubleType()),
        T.StructField("PLNTY", T.StringType()),
        T.StructField("UOMGR", T.StringType()),
        T.StructField("UMRSL", T.StringType()),
        T.StructField("ABFAC", T.DoubleType()),
        T.StructField("SFCPF", T.StringType()),
        T.StructField("SHFLG", T.StringType()),
        T.StructField("SHZET", T.StringType()),
        T.StructField("MDACH", T.StringType()),
        T.StructField("KZECH", T.StringType()),
        T.StructField("MEGRU", T.StringType()),
        T.StructField("MFRGR", T.StringType()),
        T.StructField("VKUMC", T.DoubleType()),
        T.StructField("VKTRW", T.DoubleType()),
        T.StructField("KZAGL", T.StringType()),
        T.StructField("FVIDK", T.StringType()),
        T.StructField("FXPRU", T.StringType()),
        T.StructField("LOGGR", T.StringType()),
        T.StructField("FPRFM", T.StringType()),
        T.StructField("GLGMG", T.DoubleType()),
        T.StructField("VKGLG", T.DoubleType()),
        T.StructField("INDUS", T.StringType()),
        T.StructField("MOWNR", T.StringType()),
        T.StructField("MOGRU", T.StringType()),
        T.StructField("CASNR", T.StringType()),
        T.StructField("GPNUM", T.StringType()),
        T.StructField("STEUC", T.StringType()),
        T.StructField("FABKZ", T.StringType()),
        T.StructField("MATGR", T.StringType()),
        T.StructField("VSPVB", T.StringType()),
        T.StructField("DPLFS", T.StringType()),
        T.StructField("DPLPU", T.StringType()),
        T.StructField("DPLHO", T.DoubleType()),
        T.StructField("MINLS", T.DoubleType()),
        T.StructField("MAXLS", T.DoubleType()),
        T.StructField("FIXLS", T.DoubleType()),
        T.StructField("LTINC", T.DoubleType()),
        T.StructField("COMPL", T.StringType()),
        T.StructField("CONVT", T.StringType()),
        T.StructField("SHPRO", T.StringType()),
        T.StructField("AHDIS", T.StringType()),
        T.StructField("DIBER", T.StringType()),
        T.StructField("KZPSP", T.StringType()),
        T.StructField("OCMPF", T.StringType()),
        T.StructField("APOKZ", T.StringType()),
        T.StructField("MCRUE", T.StringType()),
        T.StructField("LFMON", T.StringType()),
        T.StructField("LFGJA", T.StringType()),
        T.StructField("EISLO", T.DoubleType()),
        T.StructField("NCOST", T.StringType()),
        T.StructField("ROTATION_DATE", T.StringType()),
        T.StructField("UCHKZ", T.StringType()),
        T.StructField("UCMAT", T.StringType()),
        T.StructField("ZZREVIEWDT", T.DateType()),
        T.StructField("ZZGATNEXT", T.StringType()),
        T.StructField("ZZICM_COGS", T.StringType()),
        T.StructField("ZZAPO_MRPTYPE", T.StringType()),
        T.StructField("ZZMSDS_REQ", T.StringType()),
        T.StructField("MATNR_CLEAN", T.StringType()),
        T.StructField("sur_pkey", T.StringType()),
        T.StructField("SOURCE_SYSTEM_ERP", T.StringType()),
    ]
)


MBEW_SCHEMA = T.StructType(
    [
        T.StructField("MANDT", T.StringType()),
        T.StructField("MATNR", T.StringType()),
        T.StructField("BWKEY", T.StringType()),
        T.StructField("BWTAR", T.StringType()),
        T.StructField("LVORM", T.StringType()),
        T.StructField("LBKUM", T.DoubleType()),
        T.StructField("SALK3", T.DoubleType()),
        T.StructField("VPRSV", T.StringType()),
        T.StructField("VERPR", T.DoubleType()),
        T.StructField("STPRS", T.DoubleType()),
        T.StructField("PEINH", T.DoubleType()),
        T.StructField("BKLAS", T.StringType()),
        T.StructField("SALKV", T.DoubleType()),
        T.StructField("VMKUM", T.DoubleType()),
        T.StructField("VMSAL", T.DoubleType()),
        T.StructField("VMVPR", T.StringType()),
        T.StructField("VMVER", T.DoubleType()),
        T.StructField("VMSTP", T.DoubleType()),
        T.StructField("VMPEI", T.DoubleType()),
        T.StructField("VMBKL", T.StringType()),
        T.StructField("VMSAV", T.DoubleType()),
        T.StructField("VJKUM", T.DoubleType()),
        T.StructField("VJSAL", T.DoubleType()),
        T.StructField("VJVPR", T.StringType()),
        T.StructField("VJVER", T.DoubleType()),
        T.StructField("VJSTP", T.DoubleType()),
        T.StructField("VJPEI", T.DoubleType()),
        T.StructField("VJBKL", T.StringType()),
        T.StructField("VJSAV", T.DoubleType()),
        T.StructField("LFGJA", T.StringType()),
        T.StructField("LFMON", T.StringType()),
        T.StructField("BWTTY", T.StringType()),
        T.StructField("STPRV", T.DoubleType()),
        T.StructField("LAEPR", T.DateType()),
        T.StructField("ZKPRS", T.DoubleType()),
        T.StructField("ZKDAT", T.DateType()),
        T.StructField("BWPRS", T.DoubleType()),
        T.StructField("BWPRH", T.DoubleType()),
        T.StructField("VJBWS", T.DoubleType()),
        T.StructField("VJBWH", T.DoubleType()),
        T.StructField("VVJSL", T.DoubleType()),
        T.StructField("VVJLB", T.DoubleType()),
        T.StructField("VVMLB", T.DoubleType()),
        T.StructField("VVSAL", T.DoubleType()),
        T.StructField("ZPLPR", T.DoubleType()),
        T.StructField("ZPLP1", T.DoubleType()),
        T.StructField("ZPLP2", T.DoubleType()),
        T.StructField("ZPLP3", T.DoubleType()),
        T.StructField("ZPLD1", T.DateType()),
        T.StructField("ZPLD2", T.DateType()),
        T.StructField("ZPLD3", T.DateType()),
        T.StructField("PPERZ", T.StringType()),
        T.StructField("PPERL", T.StringType()),
        T.StructField("PPERV", T.StringType()),
        T.StructField("KALKZ", T.StringType()),
        T.StructField("KALKL", T.StringType()),
        T.StructField("KALKV", T.StringType()),
        T.StructField("KALSC", T.StringType()),
        T.StructField("XLIFO", T.StringType()),
        T.StructField("MYPOL", T.StringType()),
        T.StructField("BWPH1", T.DoubleType()),
        T.StructField("BWPS1", T.DoubleType()),
        T.StructField("ABWKZ", T.StringType()),
        T.StructField("PSTAT", T.StringType()),
        T.StructField("KALN1", T.StringType()),
        T.StructField("KALNR", T.StringType()),
        T.StructField("BWVA1", T.StringType()),
        T.StructField("BWVA2", T.StringType()),
        T.StructField("BWVA3", T.StringType()),
        T.StructField("VERS1", T.StringType()),
        T.StructField("VERS2", T.StringType()),
        T.StructField("VERS3", T.StringType()),
        T.StructField("HRKFT", T.StringType()),
        T.StructField("KOSGR", T.StringType()),
        T.StructField("PPRDZ", T.StringType()),
        T.StructField("PPRDL", T.StringType()),
        T.StructField("PPRDV", T.StringType()),
        T.StructField("PDATZ", T.StringType()),
        T.StructField("PDATL", T.StringType()),
        T.StructField("PDATV", T.StringType()),
        T.StructField("EKALR", T.StringType()),
        T.StructField("VPLPR", T.DoubleType()),
        T.StructField("MLMAA", T.StringType()),
        T.StructField("MLAST", T.StringType()),
        T.StructField("LPLPR", T.DoubleType()),
        T.StructField("VKSAL", T.DoubleType()),
        T.StructField("HKMAT", T.StringType()),
        T.StructField("SPERW", T.StringType()),
        T.StructField("KZIWL", T.StringType()),
        T.StructField("WLINL", T.DateType()),
        T.StructField("ABCIW", T.StringType()),
        T.StructField("BWSPA", T.DoubleType()),
        T.StructField("LPLPX", T.DoubleType()),
        T.StructField("VPLPX", T.DoubleType()),
        T.StructField("FPLPX", T.DoubleType()),
        T.StructField("LBWST", T.StringType()),
        T.StructField("VBWST", T.StringType()),
        T.StructField("FBWST", T.StringType()),
        T.StructField("EKLAS", T.StringType()),
        T.StructField("QKLAS", T.StringType()),
        T.StructField("MTUSE", T.StringType()),
        T.StructField("MTORG", T.StringType()),
        T.StructField("OWNPR", T.StringType()),
        T.StructField("XBEWM", T.StringType()),
        T.StructField("BWPEI", T.DoubleType()),
        T.StructField("MBRUE", T.StringType()),
        T.StructField("OKLAS", T.StringType()),
        T.StructField("OIPPINV", T.StringType()),
        T.StructField("MATNR_CLEAN", T.StringType()),
        T.StructField("sur_pkey", T.StringType()),
    ]
)

T001W_SCHEMA = T.StructType(
    [
        T.StructField("MANDT", T.StringType()),
        T.StructField("WERKS", T.StringType()),
        T.StructField("NAME1", T.StringType()),
        T.StructField("BWKEY", T.StringType()),
        T.StructField("KUNNR", T.StringType()),
        T.StructField("LIFNR", T.StringType()),
        T.StructField("FABKL", T.StringType()),
        T.StructField("NAME2", T.StringType()),
        T.StructField("STRAS", T.StringType()),
        T.StructField("PFACH", T.StringType()),
        T.StructField("PSTLZ", T.StringType()),
        T.StructField("ORT01", T.StringType()),
        T.StructField("EKORG", T.StringType()),
        T.StructField("VKORG", T.StringType()),
        T.StructField("CHAZV", T.StringType()),
        T.StructField("KKOWK", T.StringType()),
        T.StructField("KORDB", T.StringType()),
        T.StructField("BEDPL", T.StringType()),
        T.StructField("LAND1", T.StringType()),
        T.StructField("REGIO", T.StringType()),
        T.StructField("COUNC", T.StringType()),
        T.StructField("CITYC", T.StringType()),
        T.StructField("ADRNR", T.StringType()),
        T.StructField("IWERK", T.StringType()),
        T.StructField("TXJCD", T.StringType()),
        T.StructField("VTWEG", T.StringType()),
        T.StructField("SPART", T.StringType()),
        T.StructField("SPRAS", T.StringType()),
        T.StructField("WKSOP", T.StringType()),
        T.StructField("AWSLS", T.StringType()),
        T.StructField("CHAZV_OLD", T.StringType()),
        T.StructField("VLFKZ", T.StringType()),
        T.StructField("BZIRK", T.StringType()),
        T.StructField("ZONE1", T.StringType()),
        T.StructField("TAXIW", T.StringType()),
        T.StructField("BZQHL", T.StringType()),
        T.StructField("LET01", T.DoubleType()),
        T.StructField("LET02", T.DoubleType()),
        T.StructField("LET03", T.DoubleType()),
        T.StructField("TXNAM_MA1", T.StringType()),
        T.StructField("TXNAM_MA2", T.StringType()),
        T.StructField("TXNAM_MA3", T.StringType()),
        T.StructField("BETOL", T.StringType()),
        T.StructField("J_1BBRANCH", T.StringType()),
        T.StructField("VTBFI", T.StringType()),
        T.StructField("FPRFW", T.StringType()),
        T.StructField("ACHVM", T.StringType()),
        T.StructField("DVSART", T.StringType()),
        T.StructField("NODETYPE", T.StringType()),
        T.StructField("NSCHEMA", T.StringType()),
        T.StructField("PKOSA", T.StringType()),
        T.StructField("MISCH", T.StringType()),
        T.StructField("MGVUPD", T.StringType()),
        T.StructField("VSTEL", T.StringType()),
        T.StructField("MGVLAUPD", T.StringType()),
        T.StructField("SOURCING", T.StringType()),
        T.StructField("sur_pkey", T.StringType()),
    ]
)

T001K_SCHEMA = T.StructType(
    [
        T.StructField("MANDT", T.StringType()),
        T.StructField("BWKEY", T.StringType()),
        T.StructField("BUKRS", T.StringType()),
        T.StructField("BWMOD", T.StringType()),
        T.StructField("XBKNG", T.StringType()),
        T.StructField("MLBWA", T.StringType()),
        T.StructField("MLBWV", T.StringType()),
        T.StructField("XVKBW", T.StringType()),
        T.StructField("ERKLAERKOM", T.StringType()),
        T.StructField("UPROF", T.StringType()),
        T.StructField("WBPRO", T.StringType()),
        T.StructField("MLAST", T.StringType()),
        T.StructField("MLASV", T.StringType()),
        T.StructField("BDIFP", T.DoubleType()),
        T.StructField("XLBPD", T.StringType()),
        T.StructField("XEWRX", T.StringType()),
        T.StructField("X2FDO", T.StringType()),
        T.StructField("PRSFR", T.StringType()),
        T.StructField("MLCCS", T.StringType()),
        T.StructField("XEFRE", T.StringType()),
        T.StructField("EFREJ", T.StringType()),
        T.StructField("sur_pkey", T.StringType()),
    ]
)

T001_SCHEMA = T.StructType(
    [
        T.StructField("MANDT", T.StringType()),
        T.StructField("BUKRS", T.StringType()),
        T.StructField("BUTXT", T.StringType()),
        T.StructField("ORT01", T.StringType()),
        T.StructField("LAND1", T.StringType()),
        T.StructField("WAERS", T.StringType()),
        T.StructField("SPRAS", T.StringType()),
        T.StructField("KTOPL", T.StringType()),
        T.StructField("WAABW", T.StringType()),
        T.StructField("PERIV", T.StringType()),
        T.StructField("KOKFI", T.StringType()),
        T.StructField("RCOMP", T.StringType()),
        T.StructField("ADRNR", T.StringType()),
        T.StructField("STCEG", T.StringType()),
        T.StructField("FIKRS", T.StringType()),
        T.StructField("XFMCO", T.StringType()),
        T.StructField("XFMCB", T.StringType()),
        T.StructField("XFMCA", T.StringType()),
        T.StructField("TXJCD", T.StringType()),
        T.StructField("FMHRDATE", T.DateType()),
        T.StructField("BUVAR", T.StringType()),
        T.StructField("FDBUK", T.StringType()),
        T.StructField("XFDIS", T.StringType()),
        T.StructField("XVALV", T.StringType()),
        T.StructField("XSKFN", T.StringType()),
        T.StructField("KKBER", T.StringType()),
        T.StructField("XMWSN", T.StringType()),
        T.StructField("MREGL", T.StringType()),
        T.StructField("XGSBE", T.StringType()),
        T.StructField("XGJRV", T.StringType()),
        T.StructField("XKDFT", T.StringType()),
        T.StructField("XPROD", T.StringType()),
        T.StructField("XEINK", T.StringType()),
        T.StructField("XJVAA", T.StringType()),
        T.StructField("XVVWA", T.StringType()),
        T.StructField("XSLTA", T.StringType()),
        T.StructField("XFDMM", T.StringType()),
        T.StructField("XFDSD", T.StringType()),
        T.StructField("XEXTB", T.StringType()),
        T.StructField("EBUKR", T.StringType()),
        T.StructField("KTOP2", T.StringType()),
        T.StructField("UMKRS", T.StringType()),
        T.StructField("BUKRS_GLOB", T.StringType()),
        T.StructField("FSTVA", T.StringType()),
        T.StructField("OPVAR", T.StringType()),
        T.StructField("XCOVR", T.StringType()),
        T.StructField("TXKRS", T.StringType()),
        T.StructField("WFVAR", T.StringType()),
        T.StructField("XBBBF", T.StringType()),
        T.StructField("XBBBE", T.StringType()),
        T.StructField("XBBBA", T.StringType()),
        T.StructField("XBBKO", T.StringType()),
        T.StructField("XSTDT", T.StringType()),
        T.StructField("MWSKV", T.StringType()),
        T.StructField("MWSKA", T.StringType()),
        T.StructField("IMPDA", T.StringType()),
        T.StructField("XNEGP", T.StringType()),
        T.StructField("XKKBI", T.StringType()),
        T.StructField("WT_NEWWT", T.StringType()),
        T.StructField("PP_PDATE", T.StringType()),
        T.StructField("INFMT", T.StringType()),
        T.StructField("FSTVARE", T.StringType()),
        T.StructField("KOPIM", T.StringType()),
        T.StructField("DKWEG", T.StringType()),
        T.StructField("OFFSACCT", T.StringType()),
        T.StructField("BAPOVAR", T.StringType()),
        T.StructField("XCOS", T.StringType()),
        T.StructField("XCESSION", T.StringType()),
        T.StructField("XSPLT", T.StringType()),
        T.StructField("SURCCM", T.StringType()),
        T.StructField("DTPROV", T.StringType()),
        T.StructField("DTAMTC", T.StringType()),
        T.StructField("DTTAXC", T.StringType()),
        T.StructField("DTTDSP", T.StringType()),
        T.StructField("FM_DERIVE_ACC", T.StringType()),
        T.StructField("sur_pkey", T.StringType()),
    ]
)

AFKO_SCHEMA = T.StructType(
    [
        T.StructField("AUFNR", T.StringType()),
        T.StructField("MANDT", T.StringType()),
        T.StructField("GLTRP", T.DateType()),
        T.StructField("GSTRP", T.DateType()),
        T.StructField("FTRMS", T.DateType()),
        T.StructField("GLTRS", T.DateType()),
        T.StructField("GSTRS", T.DateType()),
        T.StructField("GSTRI", T.DateType()),
        T.StructField("GETRI", T.DateType()),
        T.StructField("GLTRI", T.DateType()),
        T.StructField("FTRMI", T.DateType()),
        T.StructField("FTRMP", T.DateType()),
        T.StructField("RSNUM", T.StringType()),
        T.StructField("GASMG", T.DoubleType()),
        T.StructField("GAMNG", T.DoubleType()),
        T.StructField("GMEIN", T.StringType()),
        T.StructField("PLNBEZ", T.StringType()),
        T.StructField("PLNTY", T.StringType()),
        T.StructField("PLNNR", T.StringType()),
        T.StructField("PLNAW", T.StringType()),
        T.StructField("PLNAL", T.StringType()),
        T.StructField("PVERW", T.StringType()),
        T.StructField("PLAUF", T.DateType()),
        T.StructField("PLSVB", T.DoubleType()),
        T.StructField("PLNME", T.StringType()),
        T.StructField("PLSVN", T.DoubleType()),
        T.StructField("PDATV", T.DateType()),
        T.StructField("PAENR", T.StringType()),
        T.StructField("PLGRP", T.StringType()),
        T.StructField("LODIV", T.DoubleType()),
        T.StructField("STLTY", T.StringType()),
        T.StructField("STLBEZ", T.StringType()),
        T.StructField("STLST", T.StringType()),
        T.StructField("STLNR", T.StringType()),
        T.StructField("SDATV", T.DateType()),
        T.StructField("SBMNG", T.DoubleType()),
        T.StructField("SBMEH", T.StringType()),
        T.StructField("SAENR", T.StringType()),
        T.StructField("STLAL", T.StringType()),
        T.StructField("STLAN", T.StringType()),
        T.StructField("SLSVN", T.DoubleType()),
        T.StructField("SLSBS", T.DoubleType()),
        T.StructField("AUFLD", T.DateType()),
        T.StructField("DISPO", T.StringType()),
        T.StructField("AUFPL", T.StringType()),
        T.StructField("FEVOR", T.StringType()),
        T.StructField("FHORI", T.StringType()),
        T.StructField("TERKZ", T.StringType()),
        T.StructField("REDKZ", T.StringType()),
        T.StructField("APRIO", T.StringType()),
        T.StructField("NTZUE", T.StringType()),
        T.StructField("VORUE", T.StringType()),
        T.StructField("PROFID", T.StringType()),
        T.StructField("VORGZ", T.StringType()),
        T.StructField("SICHZ", T.StringType()),
        T.StructField("FREIZ", T.StringType()),
        T.StructField("UPTER", T.StringType()),
        T.StructField("BEDID", T.StringType()),
        T.StructField("PRONR", T.StringType()),
        T.StructField("ZAEHL", T.StringType()),
        T.StructField("MZAEHL", T.StringType()),
        T.StructField("ZKRIZ", T.StringType()),
        T.StructField("PRUEFLOS", T.StringType()),
        T.StructField("KLVARP", T.StringType()),
        T.StructField("KLVARI", T.StringType()),
        T.StructField("RGEKZ", T.StringType()),
        T.StructField("PLART", T.StringType()),
        T.StructField("FLG_AOB", T.StringType()),
        T.StructField("FLG_ARBEI", T.StringType()),
        T.StructField("GLTPP", T.DateType()),
        T.StructField("GSTPP", T.DateType()),
        T.StructField("GLTPS", T.DateType()),
        T.StructField("GSTPS", T.DateType()),
        T.StructField("FTRPS", T.DateType()),
        T.StructField("RDKZP", T.StringType()),
        T.StructField("TRKZP", T.StringType()),
        T.StructField("RUECK", T.StringType()),
        T.StructField("RMZHL", T.StringType()),
        T.StructField("IGMNG", T.DoubleType()),
        T.StructField("RATID", T.StringType()),
        T.StructField("GROID", T.StringType()),
        T.StructField("CUOBJ", T.StringType()),
        T.StructField("GLUZS", T.StringType()),
        T.StructField("GSUZS", T.StringType()),
        T.StructField("REVLV", T.StringType()),
        T.StructField("RSHTY", T.StringType()),
        T.StructField("RSHID", T.StringType()),
        T.StructField("RSNTY", T.StringType()),
        T.StructField("RSNID", T.StringType()),
        T.StructField("NAUTERM", T.StringType()),
        T.StructField("NAUCOST", T.StringType()),
        T.StructField("STUFE", T.DoubleType()),
        T.StructField("WEGXX", T.DoubleType()),
        T.StructField("VWEGX", T.DoubleType()),
        T.StructField("ARSNR", T.StringType()),
        T.StructField("ARSPS", T.StringType()),
        T.StructField("MAUFNR", T.StringType()),
        T.StructField("LKNOT", T.StringType()),
        T.StructField("RKNOT", T.StringType()),
        T.StructField("PRODNET", T.StringType()),
        T.StructField("IASMG", T.DoubleType()),
        T.StructField("ABARB", T.StringType()),
        T.StructField("AUFNT", T.StringType()),
        T.StructField("AUFPT", T.StringType()),
        T.StructField("APLZT", T.StringType()),
        T.StructField("NO_DISP", T.StringType()),
        T.StructField("CSPLIT", T.StringType()),
        T.StructField("AENNR", T.StringType()),
        T.StructField("CY_SEQNR", T.StringType()),
        T.StructField("BREAKS", T.StringType()),
        T.StructField("VORGZ_TRM", T.DoubleType()),
        T.StructField("SICHZ_TRM", T.DoubleType()),
        T.StructField("TRMDT", T.DateType()),
        T.StructField("GLUZP", T.StringType()),
        T.StructField("GSUZP", T.StringType()),
        T.StructField("GSUZI", T.StringType()),
        T.StructField("GEUZI", T.StringType()),
        T.StructField("GLUPP", T.StringType()),
        T.StructField("GSUPP", T.StringType()),
        T.StructField("GLUPS", T.StringType()),
        T.StructField("GSUPS", T.StringType()),
        T.StructField("CHSCH", T.StringType()),
        T.StructField("KAPT_VORGZ", T.StringType()),
        T.StructField("KAPT_SICHZ", T.StringType()),
        T.StructField("LEAD_AUFNR", T.StringType()),
        T.StructField("PNETSTARTD", T.DateType()),
        T.StructField("PNETSTARTT", T.StringType()),
        T.StructField("PNETENDD", T.DateType()),
        T.StructField("PNETENDT", T.StringType()),
        T.StructField("KBED", T.StringType()),
        T.StructField("KKALKR", T.StringType()),
        T.StructField("SFCPF", T.StringType()),
        T.StructField("RMNGA", T.DoubleType()),
        T.StructField("GSBTR", T.DateType()),
        T.StructField("VFMNG", T.DoubleType()),
        T.StructField("NOPCOST", T.StringType()),
        T.StructField("NETZKONT", T.StringType()),
        T.StructField("ATRKZ", T.StringType()),
        T.StructField("OBJTYPE", T.StringType()),
        T.StructField("CH_PROC", T.StringType()),
        T.StructField("KAPVERSA", T.StringType()),
        T.StructField("COLORDPROC", T.StringType()),
        T.StructField("KZERB", T.StringType()),
        T.StructField("CONF_KEY", T.StringType()),
        T.StructField("ST_ARBID", T.StringType()),
        T.StructField("VSNMR_V", T.StringType()),
        T.StructField("TERHW", T.StringType()),
        T.StructField("SPLSTAT", T.StringType()),
        T.StructField("COSTUPD", T.StringType()),
        T.StructField("RMANR", T.StringType()),
        T.StructField("POSNR_RMA", T.StringType()),
        T.StructField("POSNV_RMA", T.StringType()),
        T.StructField("sur_pkey", T.StringType()),
        T.StructField("SOURCE_SYSTEM_ERP", T.StringType()),
    ]
)

AFPO_SCHEMA = T.StructType(
    [
        T.StructField("AUFNR", T.StringType()),
        T.StructField("MANDT", T.StringType()),
        T.StructField("POSNR", T.StringType()),
        T.StructField("PSOBS", T.StringType()),
        T.StructField("QUNUM", T.StringType()),
        T.StructField("QUPOS", T.StringType()),
        T.StructField("PROJN", T.StringType()),
        T.StructField("PLNUM", T.StringType()),
        T.StructField("STRMP", T.DateType()),
        T.StructField("ETRMP", T.DateType()),
        T.StructField("KDAUF", T.StringType()),
        T.StructField("KDPOS", T.StringType()),
        T.StructField("KDEIN", T.StringType()),
        T.StructField("BESKZ", T.StringType()),
        T.StructField("PSAMG", T.DoubleType()),
        T.StructField("PSMNG", T.DoubleType()),
        T.StructField("WEMNG", T.DoubleType()),
        T.StructField("IAMNG", T.DoubleType()),
        T.StructField("AMEIN", T.StringType()),
        T.StructField("MEINS", T.StringType()),
        T.StructField("MATNR", T.StringType()),
        T.StructField("PAMNG", T.DoubleType()),
        T.StructField("PGMNG", T.DoubleType()),
        T.StructField("KNTTP", T.StringType()),
        T.StructField("TPAUF", T.StringType()),
        T.StructField("LTRMI", T.DateType()),
        T.StructField("LTRMP", T.DateType()),
        T.StructField("KALNR", T.StringType()),
        T.StructField("UEBTO", T.DoubleType()),
        T.StructField("UEBTK", T.StringType()),
        T.StructField("UNTTO", T.DoubleType()),
        T.StructField("INSMK", T.StringType()),
        T.StructField("WEPOS", T.StringType()),
        T.StructField("BWTAR", T.StringType()),
        T.StructField("BWTTY", T.StringType()),
        T.StructField("PWERK", T.StringType()),
        T.StructField("LGORT", T.StringType()),
        T.StructField("UMREZ", T.DoubleType()),
        T.StructField("UMREN", T.DoubleType()),
        T.StructField("WEBAZ", T.DoubleType()),
        T.StructField("ELIKZ", T.StringType()),
        T.StructField("SAFNR", T.StringType()),
        T.StructField("VERID", T.StringType()),
        T.StructField("SERNR", T.StringType()),
        T.StructField("TECHS", T.StringType()),
        T.StructField("DWERK", T.StringType()),
        T.StructField("DAUTY", T.StringType()),
        T.StructField("DAUAT", T.StringType()),
        T.StructField("DGLTP", T.DateType()),
        T.StructField("DGLTS", T.DateType()),
        T.StructField("DFREI", T.StringType()),
        T.StructField("DNREL", T.StringType()),
        T.StructField("VERTO", T.StringType()),
        T.StructField("SOBKZ", T.StringType()),
        T.StructField("KZVBR", T.StringType()),
        T.StructField("WEWRT", T.DoubleType()),
        T.StructField("WEUNB", T.StringType()),
        T.StructField("ABLAD", T.StringType()),
        T.StructField("WEMPF", T.StringType()),
        T.StructField("CHARG", T.StringType()),
        T.StructField("GSBER", T.StringType()),
        T.StructField("WEAED", T.StringType()),
        T.StructField("CUOBJ", T.StringType()),
        T.StructField("KBNKZ", T.StringType()),
        T.StructField("ARSNR", T.StringType()),
        T.StructField("ARSPS", T.StringType()),
        T.StructField("KRSNR", T.StringType()),
        T.StructField("KRSPS", T.StringType()),
        T.StructField("KCKEY", T.StringType()),
        T.StructField("RTP01", T.StringType()),
        T.StructField("RTP02", T.StringType()),
        T.StructField("RTP03", T.StringType()),
        T.StructField("RTP04", T.StringType()),
        T.StructField("KSVON", T.DateType()),
        T.StructField("KSBIS", T.DateType()),
        T.StructField("OBJNP", T.StringType()),
        T.StructField("NDISR", T.StringType()),
        T.StructField("VFMNG", T.DoubleType()),
        T.StructField("GSBTR", T.DateType()),
        T.StructField("KZAVC", T.StringType()),
        T.StructField("KZBWS", T.StringType()),
        T.StructField("XLOEK", T.StringType()),
        T.StructField("SERNP", T.StringType()),
        T.StructField("ANZSN", T.IntegerType()),
        T.StructField("OBJTYPE", T.StringType()),
        T.StructField("CH_PROC", T.StringType()),
        T.StructField("FXPRU", T.StringType()),
        T.StructField("CUOBJ_ROOT", T.StringType()),
        T.StructField("BERID", T.StringType()),
        T.StructField("TECHS_COPY", T.StringType()),
        T.StructField("MATNR_CLEAN", T.StringType()),
        T.StructField("sur_pkey", T.StringType()),
        T.StructField("SOURCE_SYSTEM_ERP", T.StringType()),
    ]
)

AUFK_SCHEMA = T.StructType(
    [
        T.StructField("AUFNR", T.StringType()),
        T.StructField("MANDT", T.StringType()),
        T.StructField("AUART", T.StringType()),
        T.StructField("AUTYP", T.StringType()),
        T.StructField("REFNR", T.StringType()),
        T.StructField("ERNAM", T.StringType()),
        T.StructField("ERDAT", T.DateType()),
        T.StructField("AENAM", T.StringType()),
        T.StructField("AEDAT", T.DateType()),
        T.StructField("KTEXT", T.StringType()),
        T.StructField("LTEXT", T.StringType()),
        T.StructField("BUKRS", T.StringType()),
        T.StructField("WERKS", T.StringType()),
        T.StructField("GSBER", T.StringType()),
        T.StructField("KOKRS", T.StringType()),
        T.StructField("CCKEY", T.StringType()),
        T.StructField("KOSTV", T.StringType()),
        T.StructField("STORT", T.StringType()),
        T.StructField("SOWRK", T.StringType()),
        T.StructField("ASTKZ", T.StringType()),
        T.StructField("WAERS", T.StringType()),
        T.StructField("ASTNR", T.StringType()),
        T.StructField("STDAT", T.DateType()),
        T.StructField("ESTNR", T.StringType()),
        T.StructField("PHAS0", T.StringType()),
        T.StructField("PHAS1", T.StringType()),
        T.StructField("PHAS2", T.StringType()),
        T.StructField("PHAS3", T.StringType()),
        T.StructField("PDAT1", T.DateType()),
        T.StructField("PDAT2", T.DateType()),
        T.StructField("PDAT3", T.DateType()),
        T.StructField("IDAT1", T.DateType()),
        T.StructField("IDAT2", T.DateType()),
        T.StructField("IDAT3", T.DateType()),
        T.StructField("OBJID", T.StringType()),
        T.StructField("VOGRP", T.StringType()),
        T.StructField("LOEKZ", T.StringType()),
        T.StructField("PLGKZ", T.StringType()),
        T.StructField("KVEWE", T.StringType()),
        T.StructField("KAPPL", T.StringType()),
        T.StructField("KALSM", T.StringType()),
        T.StructField("ZSCHL", T.StringType()),
        T.StructField("ABKRS", T.StringType()),
        T.StructField("KSTAR", T.StringType()),
        T.StructField("KOSTL", T.StringType()),
        T.StructField("SAKNR", T.StringType()),
        T.StructField("SETNM", T.StringType()),
        T.StructField("CYCLE", T.StringType()),
        T.StructField("SDATE", T.DateType()),
        T.StructField("SEQNR", T.StringType()),
        T.StructField("USER0", T.StringType()),
        T.StructField("USER1", T.StringType()),
        T.StructField("USER2", T.StringType()),
        T.StructField("USER3", T.StringType()),
        T.StructField("USER4", T.DoubleType()),
        T.StructField("USER5", T.DateType()),
        T.StructField("USER6", T.StringType()),
        T.StructField("USER7", T.DateType()),
        T.StructField("USER8", T.DateType()),
        T.StructField("USER9", T.StringType()),
        T.StructField("OBJNR", T.StringType()),
        T.StructField("PRCTR", T.StringType()),
        T.StructField("PSPEL", T.StringType()),
        T.StructField("AWSLS", T.StringType()),
        T.StructField("ABGSL", T.StringType()),
        T.StructField("TXJCD", T.StringType()),
        T.StructField("FUNC_AREA", T.StringType()),
        T.StructField("SCOPE", T.StringType()),
        T.StructField("PLINT", T.StringType()),
        T.StructField("KDAUF", T.StringType()),
        T.StructField("KDPOS", T.StringType()),
        T.StructField("AUFEX", T.StringType()),
        T.StructField("IVPRO", T.StringType()),
        T.StructField("LOGSYSTEM", T.StringType()),
        T.StructField("FLG_MLTPS", T.StringType()),
        T.StructField("ABUKR", T.StringType()),
        T.StructField("AKSTL", T.StringType()),
        T.StructField("SIZECL", T.StringType()),
        T.StructField("IZWEK", T.StringType()),
        T.StructField("UMWKZ", T.StringType()),
        T.StructField("KSTEMPF", T.StringType()),
        T.StructField("ZSCHM", T.StringType()),
        T.StructField("PKOSA", T.StringType()),
        T.StructField("ANFAUFNR", T.StringType()),
        T.StructField("PROCNR", T.StringType()),
        T.StructField("PROTY", T.StringType()),
        T.StructField("RSORD", T.StringType()),
        T.StructField("BEMOT", T.StringType()),
        T.StructField("ADRNRA", T.StringType()),
        T.StructField("ERFZEIT", T.StringType()),
        T.StructField("AEZEIT", T.StringType()),
        T.StructField("CSTG_VRNT", T.StringType()),
        T.StructField("COSTESTNR", T.StringType()),
        T.StructField("ZZPRO_RSCHL_CD", T.StringType()),
        T.StructField("ZZBDDAT", T.DateType()),
        T.StructField("ZZGLTRP_ORIG", T.DateType()),
        T.StructField("ZZPRO_TEXT", T.StringType()),
        T.StructField("ZZSP_REVIEW", T.StringType()),
        T.StructField("ZZPLPRDSTART", T.DateType()),
        T.StructField("ZZCUSTSO", T.StringType()),
        T.StructField("ZZCUSTNAME", T.StringType()),
        T.StructField("ZZITPROJECT", T.StringType()),
        T.StructField("ZZTARGETSTR", T.StringType()),
        T.StructField("VNAME", T.StringType()),
        T.StructField("RECID", T.StringType()),
        T.StructField("ETYPE", T.StringType()),
        T.StructField("OTYPE", T.StringType()),
        T.StructField("JV_JIBCL", T.StringType()),
        T.StructField("JV_JIBSA", T.StringType()),
        T.StructField("JV_OCO", T.StringType()),
        T.StructField("ZZBUSNSEG", T.StringType()),
        T.StructField("ZZSUB_BUSNSEG", T.StringType()),
        T.StructField("ZZPRODH_L1", T.StringType()),
        T.StructField("ZZPRODH_L2", T.StringType()),
        T.StructField("sur_pkey", T.StringType()),
    ]
)

Local_Material = T.StructType(
    [
        T.StructField("SOURCE_SYSTEM_ERP", T.StringType(), True),
        T.StructField("MANDT", T.StringType(), True),
        T.StructField("MATNR", T.StringType(), True),
        T.StructField("WERKS", T.StringType(), True),
        T.StructField("WEKRS", T.StringType(), True),
        T.StructField("MEINS", T.StringType(), True),
        T.StructField("GLOBAL_MATERIAL_NUMBER", T.StringType(), True),
        T.StructField("BWKEY", T.StringType(), True),
        T.StructField("NAME1", T.StringType(), True),
        T.StructField("VPRSV", T.StringType(), True),
        T.StructField("VERPR", T.DoubleType(), True),
        T.StructField("STPRS", T.DoubleType(), True),
        T.StructField("PEINH", T.IntegerType(), True),
        T.StructField("BKLAS", T.StringType(), True),
        T.StructField("BUKRS", T.StringType(), True),
        T.StructField("WAERS", T.StringType(), True),
        T.StructField("BISMT", T.StringType(), True),
        T.StructField("LVORM", T.StringType(), True),
        T.StructField("PLIFZ", T.IntegerType(), True),
        T.StructField("DZEIT", T.IntegerType(), True),
        T.StructField("DISLS", T.StringType(), True),
        T.StructField("LAEPR", T.DoubleType(), True),
        T.StructField("mtl_plant_emd", T.StringType(), True),
        T.StructField("global_mtl_id", T.StringType(), True),
        T.StructField("primary_key_intra", T.StringType(), True),
        T.StructField("primary_key_inter", T.StringType(), True),
        T.StructField("no_of_duplicates", T.IntegerType(), True),
    ]
)

Process_Order_Schema = T.StructType(
    [
        T.StructField("SOURCE_SYSTEM_ERP", T.StringType(), True),
        T.StructField("MANDT", T.StringType(), True),
        T.StructField("AUFNR", T.StringType(), True),
        T.StructField("GLTRP", T.DateType(), True),
        T.StructField("GSTRP", T.DateType(), True),
        T.StructField("FTRMS", T.DateType(), True),
        T.StructField("GLTRS", T.DateType(), True),
        T.StructField("GSTRS", T.DateType(), True),
        T.StructField("GSTRI", T.DateType(), True),
        T.StructField("GETRI", T.DateType(), True),
        T.StructField("GLTRI", T.DateType(), True),
        T.StructField("FTRMI", T.DateType(), True),
        T.StructField("FTRMP", T.DateType(), True),
        T.StructField("DISPO", T.StringType(), True),
        T.StructField("FEVOR", T.StringType(), True),
        T.StructField("PLGRP", T.StringType(), True),
        T.StructField("FHORI", T.StringType(), True),
        T.StructField("AUFPL", T.StringType(), True),
        T.StructField("POSNR", T.StringType(), True),
        T.StructField("DWERK", T.StringType(), True),
        T.StructField("MATNR", T.StringType(), True),
        T.StructField("MEINS", T.StringType(), True),
        T.StructField("KDAUF", T.StringType(), True),
        T.StructField("KDPOS", T.StringType(), True),
        T.StructField("OBJNR", T.StringType(), True),
        T.StructField("ERDAT", T.DateType(), True),
        T.StructField("ERNAM", T.StringType(), True),
        T.StructField("AUART", T.StringType(), True),
        T.StructField("ZZGLTRP_ORIG", T.DateType(), True),
        T.StructField("ZZPRO_TEXT", T.StringType(), True),
        T.StructField("GLOBAL_MATERIAL_NUMBER", T.StringType(), True),
        T.StructField("NTGEW", T.DecimalType(15, 3), True),
        T.StructField("MTART", T.StringType(), True),
        T.StructField("primary_key_intra", T.StringType(), True),
        T.StructField("primary_key_inter", T.StringType(), True),
        T.StructField("on_time_flag", T.IntegerType(), True),
        T.StructField("late_delivery_bucket", T.StringType(), True),
        T.StructField("mto_vs_mts_flag", T.StringType(), True),
        T.StructField("order_finish_timestamp", T.TimestampType(), True),
        T.StructField("order_start_timestamp", T.TimestampType(), True),
        T.StructField("actual_on_time_deviation", T.IntegerType(), True),
    ]
)

LOCAL_MATERIAL_SCHEMA = T.StructType(
    [
        T.StructField("SOURCE_SYSTEM_ERP", T.StringType(), True),
        T.StructField("MATNR", T.StringType(), True),
        T.StructField("WERKS", T.StringType(), True),
        T.StructField("MEINS", T.StringType(), True),
        T.StructField("global_material_number", T.StringType(), True),
        T.StructField("BWKEY", T.StringType(), True),
        T.StructField("NAME1", T.StringType(), True),
        T.StructField("VPRSV", T.StringType(), True),
        T.StructField("VERPR", T.DoubleType(), True),
        T.StructField("STPRS", T.DoubleType(), True),
        T.StructField("PEINH", T.DoubleType(), True),
        T.StructField("BKLAS", T.StringType(), True),
        T.StructField("WAERS", T.StringType(), True),
        T.StructField("mtl_plant_emd", T.StringType(), False),
        T.StructField("global_mtl_id", T.StringType(), True),
        T.StructField("primary_key_intra", T.StringType(), False),
        T.StructField("primary_key_inter", T.StringType(), False),
        T.StructField("no_of_duplicates", T.LongType(), False),
    ]
)


PROCESS_ORDER_SCHEMA = T.StructType(
    [
        T.StructField("SOURCE_SYSTEM_ERP", T.StringType(), True),
        T.StructField("MANDT", T.StringType(), True),
        T.StructField("GLTRP", T.DateType(), True),
        T.StructField("GSTRP", T.DateType(), True),
        T.StructField("FTRMS", T.DateType(), True),
        T.StructField("GLTRS", T.DateType(), True),
        T.StructField("GSTRS", T.DateType(), True),
        T.StructField("GSTRI", T.DateType(), True),
        T.StructField("GETRI", T.DateType(), True),
        T.StructField("GLTRI", T.DateType(), True),
        T.StructField("FTRMI", T.DateType(), True),
        T.StructField("FTRMP", T.DateType(), True),
        T.StructField("DISPO", T.StringType(), True),
        T.StructField("FEVOR", T.StringType(), True),
        T.StructField("PLGRP", T.StringType(), True),
        T.StructField("FHORI", T.StringType(), True),
        T.StructField("AUFPL", T.StringType(), True),
        T.StructField("start_date", T.DateType(), True),
        T.StructField("finish_date", T.DateType(), True),
        T.StructField("POSNR", T.StringType(), True),
        T.StructField("DWERK", T.StringType(), True),
        T.StructField("MEINS", T.StringType(), True),
        T.StructField("KDAUF", T.StringType(), True),
        T.StructField("KDPOS", T.StringType(), True),
        T.StructField("AUFNR", T.StringType(), True),
        T.StructField("OBJNR", T.StringType(), True),
        T.StructField("ERDAT", T.DateType(), True),
        T.StructField("ERNAM", T.StringType(), True),
        T.StructField("AUART", T.StringType(), True),
        T.StructField("ZZGLTRP_ORIG", T.DateType(), True),
        T.StructField("ZZPRO_TEXT", T.StringType(), True),
        T.StructField("global_material_number", T.StringType(), True),
        T.StructField("NTGEW", T.DoubleType(), True),
        T.StructField("MTART", T.StringType(), True),
        T.StructField("primary_key_intra", T.StringType(), False),
        T.StructField("primary_key_inter", T.StringType(), False),
        T.StructField("on_time_flag", T.IntegerType(), True),
        T.StructField("actual_on_time_deviation", T.IntegerType(), True),
        T.StructField("late_delivery_bucket", T.StringType(), True),
        T.StructField("mto_vs_mts_flag", T.StringType(), False),
        T.StructField("order_finish_timestamp", T.TimestampType(), True),
        T.StructField("order_start_timestamp", T.TimestampType(), True),
    ]
)


PRD_Schema_data = {
    "MARA": MARA_SCHEMA,
    "MARC": MARC_SCHEMA,
    "MBEW": MBEW_SCHEMA,
    "T001W": T001W_SCHEMA,
    "T001K": T001K_SCHEMA,
    "T001": T001_SCHEMA,
    "AFKO": AFKO_SCHEMA,
    "AFPO": AFPO_SCHEMA,
    "AUFK": AUFK_SCHEMA,
    "LOCAL_MATERIAL": LOCAL_MATERIAL_SCHEMA,
    "PROCESS_ORDER_SCHEMA": PROCESS_ORDER_SCHEMA,
}
